[tool.black]
line-length = 95
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
skip-string-normalization = true
extend-exclude = '^/(deploy|docs|ignore|legacy|notebooks)'

[tool.isort]
profile = "black"
line_length = 95
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
no_lines_before = ["STDLIB",]
lines_between_types = 1

